name: wallet_flutter
description: Nautilus - Fast, Robust & Secure NANO Wallet.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 0.7.8

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # magic:
  magic_sdk: ^2.0.0
  # magic_sdk:
  #   git:
  #     url: https://github.com/magiclabs/magic-flutter.git
  #     path: packages/magic_sdk
  #     ref: main
  # cicd:
  flutter_dotenv: ^5.0.2

  # contacts:
  flutter_contacts: ^1.1.4

  # uuid:
  uuid: ^3.0.6

  # Securely store data in a keystore
  flutter_secure_storage: ^6.0.0

  # Nano core functions
  flutter_nano_ffi:
    git:
      url: https://github.com/perishllc/flutter_nano_ffi.git
      ref: main

  # Shared prefs
  shared_preferences: ^2.0.15

  # animations
  lottie: ^2.0.0

  # intro page:
  animated_text_kit: ^4.2.2

  # Websockets
  web_socket_channel: ^2.2.0

  # ENS:
  ens_dart: ^1.0.0
  # web3dart: ^2.4.1
  # version 2.5.0 breaks things:
  web3dart: 2.4.1

  # charts:
  coingecko_api: ^1.1.0+2
  fl_chart: ^0.55.2

  # Device-specific info
  device_info_plus: ^8.0.0
  android_id: ^0.0.7

  # JSON Serialization
  json_annotation: ^4.6.0

  # Localization
  intl: ^0.17.0
  # BigDecimal alternative
  decimal: ^2.3.0

  # Logger
  logger: ^1.0.0

  # changelog:
  package_info_plus: ^1.4.2
  # package_info_plus: ^3.0.0
  flutter_markdown: ^0.6.12

  # Native webview plugin
  # webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.4.4+2

  # SQLite
  sqflite: ^2.1.0+1

  # Android/iOS path provider
  path_provider: ^2.0.11

  # TouchID/FaceID
  local_auth: ^2.1.2

  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^1.1.5

  # nfc:
  nfc_manager: ^3.2.0
  # reliably check connection status:
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.0

  # ask users to rate the app:
  rate_my_app: ^1.1.3

  # QR Codes
  qr_flutter: ^4.0.0 # Generator
  pretty_qr_code: ^2.0.2
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.6
  mobile_scanner: ^3.0.0-beta.4
  # mobile_scanner: 3.0.0-beta.1
  # Share files
  share_plus: ^6.2.0

  # File picker
  file_picker: ^5.2.0

  # Deep link support
  flutter_branch_sdk: ^6.2.1

  uni_links:
    git:
      url: https://github.com/perishllc/uni_links.git
      path: uni_links
      ref: main

  # HTTP client
  http: ^0.13.4

  # Vibrate
  flutter_vibrate: ^1.3.0

  # Toast
  oktoast: ^3.3.1

  # Push notifications
  firebase_messaging: ^14.0.4
  firebase_core: ^2.2.0
  firebase_analytics: ^10.0.5
  firebase_app_check: ^0.1.1+3
  flutter_local_notifications: ^13.0.0
  # firebase_core: ^2.1.1
  # awesome_notifications: ^0.7.4+1
  # awesome_notifications_fcm: ^0.7.4+1
  easy_cron: ^0.9.2

  # windows plugins / ffi:
  sqflite_common_ffi: ^2.1.1

  # Slidable list actions
  flutter_slidable: ^2.0.0

  # Lock helper
  synchronized: ^3.0.0

  # Service provider
  get_it: ^7.2.0

  # root / jailbreak detection
  flutter_jailbreak_detection: ^1.8.0

  # Validation utilities
  validators: ^3.0.0

  # Auto resize text widget
  auto_size_text: ^3.0.0

  # loading bar percent:
  percent_indicator: ^4.2.2

  # Avoid keyboard from overlapping text fields
  # keyboard_avoider: ^0.1.2
  keyboard_avoider:
    git:
      url: https://github.com/perishllc/keyboard_avoider
      ref: main

  # Launch external URLs
  url_launcher: ^6.0.2

  # async / general programming utilities
  quiver: ^3.1.0

  devicelocale: ^0.5.5

  # encryption helper:
  flutter_sodium:
    git:
      url: https://github.com/perishllc/flutter_sodium
      ref: main
  x25519: ^0.1.1
  encrypt: ^5.0.1

  # search bar + text highlighting:
  # searchbar_animation: ^0.0.3
  searchbar_animation: 0.0.3
  substring_highlight: ^1.0.33

  # localization:
  intl_utils: ^2.7.0

  # confetti:
  confetti: ^0.7.0

  path: ^1.8.1

  # hcaptcha:
  webview_flutter: ^3.0.4
  app_tracking_transparency: ^2.0.2+4

  # list optimization:
  keframe: ^3.0.0

  # bip39:
  ed25519_hd_key: ^2.2.0
  libcrypto: ^0.2.1

  # in app purchases:
  in_app_purchase: ^3.0.8
  flutter_rust_bridge: ^1.51.1
  ffi: ^2.0.1
  ffigen: ^7.2.2
  flutter_native_timezone: ^2.0.0
  cron: ^0.5.1
  math_expressions: ^2.3.1

flutter_intl:
  enabled: true
  class_name: Z
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
  localizely:
    project_id: 6991a0b2-4aa6-49c1-82d8-fcd38488d8b4

dependency_overrides:
  ffi: ^2.0.1
  # web3dart: 2.0.0
  # analyzer: ^4.1.0
  # dart_style: ^2.2.3
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/knyghtryda/flutter_launcher_icons
  #     ref: scaling
  uni_links_platform_interface:
    git:
      url: https://github.com/perishllc/uni_links.git
      path: uni_links_platform_interface
      ref: main
  # https://github.com/pichillilorenzo/flutter_inappwebview/issues/1223
  # flutter_inappwebview:
  #   git:
  #     url: https://github.com/rshrc/flutter_inappwebview
  #     ref: master
  # device_info_plus_platform_interface: 2.3.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  analyzer: ^4.7.0
  dart_style: ^2.2.3

  # screenshot generation:
  file: ^6.1.2
  # rust:
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: ExtraAppIcons
      fonts:
        - asset: fonts/ExtraAppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - .env
    # animations:
    - assets/animations/load-n.json
    - assets/animations/rocket.json
    - assets/animations/searching.json
    - assets/animations/loading/generic_spinner_1.json
    - assets/animations/loading/generic_spinner_2.json
    - assets/animations/loading/tri_circle_spinner.json
    - assets/animations/world-lines.json
    - assets/animations/world-plane.json
    # other assets
    - assets/logo.png
    - assets/logo.svg
    - assets/logos/nanocafe.png
    - assets/logos/redeemforme.png
    - assets/logos/onramper.png
    - assets/logos/nanswap.png
    - assets/logos/playnano.png
    - assets/logos/luckynano.png
    - assets/logos/wenano.png
    - assets/logos/perseeve.png
    # nyano assets:
    - assets/nyano/images/logos/cat-head-collar-black-1000 × 1180.png
    # illustrations:
    - assets/illustrations/transferfunds_start.svg
    - assets/illustrations/transferfunds_paperwalletonly.svg
    # changelog:
    - assets/CHANGELOG.md
    # xmr:
    - assets/xmr/
    - assets/xmr/index.html
    - assets/xmr/main.js
    - assets/xmr/monero_wallet_full.js
    - assets/xmr/monero_wallet_full.wasm
    - assets/xmr/monero_web_worker.js

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
